//Guardar lista de productos
export const SAVE_DATA_FULLFILLED = "SAVE_DATA_FULLFILLED";
export const SAVE_DATA_LOADING = "SAVE_DATA_LOADING";
export const SAVE_DATA_REJECTED = "SAVE_DATA_REJECTED";

//Agregar productos
export const ADD_DATA_FULLFILLED = "ADD_DATA_FULLFILLED";
export const ADD_DATA_LOADING = "ADD_DATA_LOAFING";
export const ADD_DATA_REJECTED = "ADD_DATA_REJECTED";

//Editar productos
export const EDIT_PRODUCT_FULLFILLED = "EDIT_PRODUCT_FULLFILLED";
export const EDIT_PRODUCT_LOADING = "EDIT_PRODUCT_LOADING";
export const EDIT_PRODUCT_REJECTED = "EDIT_PRODUCT_REJECTED";

//Eliminar productos
export const DELETE_PRODUCTS_FULLFILLED = 'DELETE_PRODUCTS_FULLFILLED';
export const DELETE_PRODUCTS_LOADING = 'DELETE_PRODUCTS_LOADING';
export const DELETE_PRODUCTS_ERROR = 'DELETE_PRODUCTS_ERROR';